### PR TITLE
define PKG_CHECK_VAR if it doesn't exist

### PR DESCRIPTION
**Pull request by kraftwerk2020**

### CODE REVIEW

**Comment by Dridi** [comment]
Hello @kraftwerk2020,

Instead of cluttering `configure.ac` I added it in a separate file, see 2c3fe7b.

Can you please confirm it fixes the build for you? I'm also trying to simplify VMOD building at least for VMOD authors and although I'm not done, I have made some progress.

Could you please try building these branches on your platform?
https://github.com/Dridi/libvmod-querystring/tree/feature/build
https://github.com/Dridi/varnish-modules/tree/feature/build

Thanks!

**Comment by kraftwerk2020** [comment]
I had to comment out AC_REQUIRE([AM_PROG_AR]) in m4/ax_vmod.m4 in both projects to get them to build.

**Comment by Dridi** [comment]
Thanks for your *very valuable* feedback, the right solution should be something like:

```
m4_ifdef([AM_PROG_AR], AC_REQUIRE([AM_PROG_AR]))
```

Are you able to build `vmod-named`'s master branch now?

**Comment by kraftwerk2020** [comment]
Yes, it built without issues.

**Comment by Dridi** [comment]
I'll close this now, thanks again for reporting the issue and testing the other branches.

**Comment by kraftwerk2020** [comment]
No problem, thanks for the work on Varnish!!

**Pull request closed without merging**
